spring:
  application:
    name: seorin
  session:
    store-type: redis
    redis:
      namespace: shboard:session
  data:
    redis:
      host: localhost
      port: 6379

server:
    port: 9090
    servlet:
      session:
        timeout: 30s
        cookie:
          name: JSESSIONID # 세션 쿠키 이름 설정
